### ISSUE TITLE
Error bridging request-reply messages with IBM MQ and NATS

### ISSUE THREAD

**Issue by chris-jansson** [nats-io/nats-jms-mq-bridge#131]
I'm trying to send a message from IBM MQ to NATS, then have my Java NATS client receive the message and return a response to the response topic, using `message.getReplyTo()`. 

I'm using `nats-bridge-admin-0.6.0-beta2` with local Docker containers for both brokers.

The request message makes it through the bridge to the client, and the client receives it and sends the response back to NATS successfully. However, the bridge throws an error and fails to return the message back to IBM MQ. 

I'm guessing my config isn't quite right, however I'm not sure what the problem is. Here's what I have:

```
---
name: "Starter Config"
dateTime:
- 2020
- 4
- 30
- 0
- 53
- 50
- 423615000
bridges:
- name: "ibmMqToNats"
  bridgeType: "REQUEST_REPLY"
  destination:
    name: "nats"
    busType: "NATS"
    subject: "requestTopic"
    clusterName: "natsCluster"
  source:
    name: "ibmMQ"
    busType: "JMS"
    subject: "DEV.QUEUE.1"
    clusterName: "ibmMqCluster"
  copyHeaders: false
  workers: 5
  tasks : 2

clusters:
  natsCluster:
    name: "natsCluster"
    properties: !<nats>
      host: "localhost"
      port: 4222
      servers: []
      config:
        io.nats.client.reconnect.wait: 3000
        io.nats.client.reconnect.max: 10
        io.nats.client.timeout: 4000
  ibmMqCluster:
    name: "ibmMqCluster"
    properties: !<jms>
      config:
        java.naming.factory.initial: "io.nats.bridge.integration.ibmmq.IbmMqInitialContextFactory"
        nats.ibm.mq.host: "tcp://localhost:1414"
        nats.ibm.mq.channel: "DEV.APP.SVRCONN"
        nats.ibm.mq.queueManager: "QM1"
        nats.ibm.mq.queueModelName: "DEV.MODEL"
        nats.ibm.mq.queueModelPrefix: "DEV*"
      userName: "app"
      password: "passw0rd"
      jmsDestinationType: "QUEUE"
```

When the bridge receives the response message from NATS, it throws this error:

```
NOT EXPECTING A REPLY CONVERT JMS TO BRIDGE MESSAGE NO JMS REPLY TO::: creatornull::: DEFAULT HANDLER CALLED null
CALLER INFO----
java.lang.Exception
	at io.nats.bridge.messages.MessageBuilder.withNoReplyHandler(MessageBuilder.java:76)
	at io.nats.bridge.jms.support.ConvertJmsMessageToBridgeMessage.apply(ConvertJmsMessageToBridgeMessage.java:64)
	at io.nats.bridge.jms.support.ConvertJmsMessageToBridgeMessage.apply(ConvertJmsMessageToBridgeMessage.java:16)
	at io.nats.bridge.jms.JMSMessageBus.lambda$convertToBusMessage$5(JMSMessageBus.java:198)
	at io.nats.bridge.util.ExceptionHandler.tryFunctionOrRethrow(ExceptionHandler.java:55)
	at io.nats.bridge.jms.JMSMessageBus.convertToBusMessage(JMSMessageBus.java:198)
	at io.nats.bridge.jms.JMSMessageBus.lambda$receive$9(JMSMessageBus.java:228)
	at io.nats.bridge.util.ExceptionHandler.tryReturnOrRethrow(ExceptionHandler.java:46)
	at io.nats.bridge.jms.JMSMessageBus.receive(JMSMessageBus.java:224)
	at io.nats.bridge.support.MessageBridgeImpl.process(MessageBridgeImpl.java:89)
	at io.nats.bridge.task.BridgeTaskRunner.process(BridgeTaskRunner.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.Exception
	at io.nats.bridge.messages.MessageBuilder.lambda$withNoReplyHandler$1(MessageBuilder.java:82)
	at io.nats.bridge.messages.BaseMessage.reply(BaseMessage.java:18)
	at io.nats.bridge.support.MessageBridgeImpl$MessageBridgeRequestReply.respond(MessageBridgeImpl.java:130)
	at io.nats.bridge.support.MessageBridgeImpl.processReplies(MessageBridgeImpl.java:98)
	at io.nats.bridge.support.MessageBridgeImpl.doProcess(MessageBridgeImpl.java:83)
	at io.nats.bridge.support.MessageBridgeImpl.process(MessageBridgeImpl.java:90)
	at io.nats.bridge.task.BridgeTaskRunner.process(BridgeTaskRunner.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by RichardHightower** [comment]
Thanks. We will take a look.

**Comment by RichardHightower** [comment]
I have included six examples. Two of the examples use IBM MQ with no QModel. 
Please try those examples.
