### ISSUE TITLE
"io.nats.bridge.tls.SslContextBuilderException: keystorePath path must exist" error when we use relative path for keystore/truststore in config yaml file

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#170]
"io.nats.bridge.tls.SslContextBuilderException: keystorePath path must exist" error when we use relative path for keystore/truststore in config yaml file.

Full error stack as below

Caused by: io.nats.bridge.tls.SslContextBuilderException: keystorePath path must exist
        at io.nats.bridge.tls.SslContextBuilder.validatePath(SslContextBuilder.java:107)
        at io.nats.bridge.tls.SslContextBuilder.getKeystorePath(SslContextBuilder.java:125)
        at io.nats.bridge.tls.SslContextBuilder.getKeyStoreKeyManagers(SslContextBuilder.java:222)
        at io.nats.bridge.tls.SslContextBuilder.build(SslContextBuilder.java:176)

**Comment by RichardHightower** [comment]
In our CI/CD set up, we use relative paths to keystone and truststore and it works. 
I am unable to reproduce this issue. 
Please advise.

**Comment by gstaware** [comment]
hi Rick, we tried but its not working with relative path for us. Can you add a way to read keystore/truststore path env variables with classpath://certs/keystore.jks or classpath://certs/truststore.jks way in the similar way like how we did for nats-bridge.yaml config file?

**Comment by gstaware** [comment]
For now, we do not have this issue hence closing it.
