### ISSUE TITLE
Truststore in .crt format is not supported

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#190]
Our automated pipeline generates truststore in .crt format. Kindly add support for crt format as well. As of now, it works with .jks format only it seems.

2020-07-13T18:58:29.623+05:30 [APP/PROC/WEB/0] [OUT] Caused by: io.nats.bridge.tls.SslContextBuilderException: Unable to load Trust store with path/etc/ssl/certs/ca-certificates.crt
2020-07-13T18:58:29.623+05:30 [APP/PROC/WEB/0] [OUT] at io.nats.bridge.tls.SslContextBuilder.getTrustStoreKeyManagers(SslContextBuilder.java:211)
2020-07-13T18:58:29.623+05:30 [APP/PROC/WEB/0] [OUT] at io.nats.bridge.tls.SslContextBuilder.build(SslContextBuilder.java:176)
2020-07-13T18:58:29.623+05:30 [APP/PROC/WEB/0] [OUT] ... 155 common frames omitted
2020-07-13T18:58:29.623+05:30 [APP/PROC/WEB/0] [OUT] Caused by: java.io.IOException: Invalid keystore format

**Comment by RichardHightower** [comment]
This is done and will be in the next release. Need some more integration testing,
