### ISSUE TITLE
Maven open issue for Config.kt

### ISSUE THREAD

**Issue by RichardHightower** [nats-io/nats-jms-mq-bridge#232]
rick, Thank you for the response. We have successfully built the app using maven. However I found some issues with Kotlin code (these are not bugs but did not work while building springboot app with maven unless I change).

Below are my comments.

 

Configuration.kt (package io.nats.bridge.admin)
It has many classes but they are not open, in maven there is no option to make these classes open as bulk. So I have manually changed their declaration to open to make it compatible to spingboot ebean requirement of final classes.
 

In file Application.kt file, at line 64, the below line is tightly coupled, could you please check with your team whether they can make it like interface and plugin App as service. So that It will be easier for us to interface with our local apps. And also reduce the overhead of changing original code every time if there any version change.
 

SpringApplication.run(Application::class.java, *args)

 

Please let us know if you have any comments or if more info needed. We thank you for your help.

**Comment by RichardHightower** [comment]
The issue does not seem to be a Kotlin issue. 

 



 
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:467)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434)
 
The issue seems to be an issue with the fat jar/shade maven plugin that you are using. 

 

If you post your pom.xml file. We can take a look. 

 

I posted some resources for you on this issue:

 

* https://github.com/nats-io/nats-jms-mq-bridge/issues/226

* https://github.com/nats-io/nats-jms-mq-bridge/issues/226#issuecomment-676617950

 

Talk to Colin if you want us to help further with the build. Those resources should get you going in the right direction with Kotlin/Maven/SpringBoot.
